### ISSUE TITLE
Delay in Listening for New Tokens on Pump.fun

### ISSUE THREAD

**Issue by creosmart** [chainstacklabs/pump-fun-bot#7]
Hello,

It seems there is a delay when listening for new tokens, which can range from 7 to 15 minutes.

Actions taken:
1) Ran listen_create_from_blocksubscribe.py.
2) Checked the token creation time on pump.fun.

Any ideas on how to troubleshoot or fix this would be greatly appreciated.

Thanks,

**Comment by creosmart** [comment]
Hello again,

It seems the delay is caused by the Chainstack WebSocket endpoint (it's working fine with another provider). Do you have any idea why?

**Comment by akegaviar** [comment]
@creosmart send a message to https://support.chainstack.com/, we'll have a look. In general, there shouldn't be delays.

**Comment by creosmart** [comment]
@akegaviar, you can close this one. I was about to take a video screenshot, but it seems everything is okay now using Chainstack's endpoints.
