### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by kuw13** [chainstacklabs/pump-fun-bot#8]
Waiting for a new token creation...
Subscribed to blocks mentioning program: 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P
New token created:
{
  "name": "First Coin The Dev Is A Baby",
  "symbol": "BABY",
  "uri": "https://ipfs.io/ipfs/QmYL2X262KyKL7KVM8Z4GLVGsYUzPQRm2LF9mBuwgUJ4jQ",
  "mint": "9xBsKEyC2131RdTLr3gXEmGLBjdS8gR7KGwwmxD3pump",
  "bondingCurve": "HztG5iw7f8gsRaRhjuUsReYy8PuCRRVUmaxc6UkRkxwc",
  "associatedBondingCurve": "Gdy1LRAWBuaCgGnYUyGAFzfoL9kALLkKmjG7hrSsigPZ",
  "user": "5aigAKtEYBNdcuarH7wrzaPHyphmkYtSxtkdkMRfPwu4"
}
Token information saved to trades/9xBsKEyC2131RdTLr3gXEmGLBjdS8gR7KGwwmxD3pump.txt
Waiting for 15 seconds for things to stabilize...
Bonding curve address: HztG5iw7f8gsRaRhjuUsReYy8PuCRRVUmaxc6UkRkxwc
Token price: 0.0000000366 SOL
Buying 0.050000 SOL worth of the new token with 20.0% slippage tolerance...
Creating associated token account (Attempt 1)...
Attempt 1 to create associated token account failed: cannot convert 'Transaction' object to bytes
Retrying in 1 seconds...
Creating associated token account (Attempt 2)...
Attempt 2 to create associated token account failed: cannot convert 'Transaction' object to bytes
Retrying in 2 seconds...
Creating associated token account (Attempt 3)...
Attempt 3 to create associated token account failed: cannot convert 'Transaction' object to bytes
Retrying in 4 seconds...
Creating associated token account (Attempt 4)...
Attempt 4 to create associated token account failed: cannot convert 'Transaction' object to bytes
Retrying in 8 seconds...
Creating associated token account (Attempt 5)...
Attempt 5 to create associated token account failed: cannot convert 'Transaction' object to bytes
Max retries reached. Unable to create associated token account.
Buy transaction failed.
Waiting for 20 seconds before selling...
Selling tokens with 20.0% slippage tolerance...
Traceback (most recent call last):
  File "/mnt/e/download/pump-fun-bot-main/pump-fun-bot-main/trade.py", line 157, in <module>
    asyncio.run(main(yolo_mode=args.yolo, match_string=args.match, bro_address=args.bro, marry_mode=args.marry))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/mnt/e/download/pump-fun-bot-main/pump-fun-bot-main/trade.py", line 140, in main
    await trade(websocket, match_string, bro_address, marry_mode, yolo_mode)
  File "/mnt/e/download/pump-fun-bot-main/pump-fun-bot-main/trade.py", line 52, in trade
    await _trade(websocket, match_string, bro_address, marry_mode, yolo_mode)
  File "/mnt/e/download/pump-fun-bot-main/pump-fun-bot-main/trade.py", line 107, in _trade
    sell_tx_hash = await sell_token(mint, bonding_curve, associated_bonding_curve, SELL_SLIPPAGE)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/download/pump-fun-bot-main/pump-fun-bot-main/sell.py", line 74, in sell_token
    token_balance = await get_token_balance(client, associated_token_account)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/download/pump-fun-bot-main/pump-fun-bot-main/sell.py", line 62, in get_token_balance
    if response.value:
       ^^^^^^^^^^^^^^
AttributeError: 'solders.rpc.errors.InvalidParamsMessage' object has no attribute 'value'

**Comment by kuw13** [comment]
any help please 
cannot convert 'Transaction' object to bytes
Max retries reached. Unable to create associated token account.

**Comment by kuw13** [comment]
now i git this ?
Creating associated token account (Attempt 1)...
Attempt 1 to create associated token account failed: 'solders.message.Message' object has no attribute 'nonce_instruction'
Retrying in 1 seconds...
Creating associated token account (Attempt 2)...
Attempt 2 to create associated token account failed: 'solders.message.Message' object has no attribute 'nonce_instruction'
Retrying in 2 seconds...
Creating associated token account (Attempt 3)...
Attempt 3 to create associated token account failed: 'solders.message.Message' object has no attribute 'nonce_instruction'
Retrying in 4 seconds...
Creating associated token account (Attempt 4)...
Attempt 4 to create associated token account failed: 'solders.message.Message' object has no attribute 'nonce_instruction'
Retrying in 8 seconds...
Creating associated token account (Attempt 5)...
Attempt 5 to create associated token account failed: 'solders.message.Message' object has no attribute 'nonce_instruction'
Max retries reached. Unable to create associated token account.
Buy transaction failed.
Waiting for 20 seconds before selling...
Selling tokens with 20.0% slippage tolerance...
Traceback (most recent call last):
  File "/mnt/e/download/pump-fun-bot-main/pump-fun-bot-main/trade.py", line 157, in <module>
    asyncio.run(main(yolo_mode=args.yolo, match_string=args.match, bro_address=args.bro, marry_mode=args.marry))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/mnt/e/download/pump-fun-bot-main/pump-fun-bot-main/trade.py", line 140, in main
    await trade(websocket, match_string, bro_address, marry_mode, yolo_mode)
  File "/mnt/e/download/pump-fun-bot-main/pump-fun-bot-main/trade.py", line 52, in trade
    await _trade(websocket, match_string, bro_address, marry_mode, yolo_mode)
  File "/mnt/e/download/pump-fun-bot-main/pump-fun-bot-main/trade.py", line 107, in _trade
    sell_tx_hash = await sell_token(mint, bonding_curve, associated_bonding_curve, SELL_SLIPPAGE)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/download/pump-fun-bot-main/pump-fun-bot-main/sell.py", line 74, in sell_token
    token_balance = await get_token_balance(client, associated_token_account)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/download/pump-fun-bot-main/pump-fun-bot-main/sell.py", line 62, in get_token_balance
    if response.value:
       ^^^^^^^^^^^^^^
AttributeError: 'solders.rpc.errors.InvalidParamsMessage' object has no attribute 'value'

**Comment by creosmart** [comment]
Check out #1

**Comment by lukiifaz** [comment]
Same.
Waiting for a new token creation...
Subscribed to blocks mentioning program: 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P
New token created:
{
  "name": "SHION AI",
  "symbol": "SHION",
  "uri": "https://ipfs.io/ipfs/QmSnYwRWFPdmZmtmhfcf7baMqLPVkD8Y3Qa7SinkMNpVMv",
  "mint": "C5othK8Ej4FA3LcNMS1Zq313zHWkYDjPr9kMfUopump",
  "bondingCurve": "Bn6fMTChWetRsSZ3XKGEuPbRLWx8k82UyyYQhw3DsUWr",
  "associatedBondingCurve": "7qCY7SDMiSLp9fLVaXC3cpZ4UYz5Nnm6RWVAYqFNvudU",
  "user": "mXNaumXZFBDL1wujYjgFBTY4mxr6rpaYSgsj1GBiXfn"
}
Token information saved to trades/C5othK8Ej4FA3LcNMS1Zq313zHWkYDjPr9kMfUopump.txt
Waiting for 15 seconds for things to stabilize...
Bonding curve address: Bn6fMTChWetRsSZ3XKGEuPbRLWx8k82UyyYQhw3DsUWr
Token price: 0.0000000321 SOL
Buying 0.010000 SOL worth of the new token with 20.0% slippage tolerance...
Creating associated token account (Attempt 1)...
Associated token account created.
Associated token account address: EboMv6xXQJohwUjg2P7fLhgHrNrBzkxKJguwUDsY8W1P
Transaction sent: https://explorer.solana.com/tx/xVTE9vzz6KrwmNXhKSn5KyyVYK4ngSV59mUquv6HSs67eHpATpewT4CPHjCZxTkJA2qsAxJAau7ZE1BbMt9MiWk
Attempt 1 failed: Unable to confirm transaction xVTE9vzz6KrwmNXhKSn5KyyVYK4ngSV59mUquv6HSs67eHpATpewT4CPHjCZxTkJA2qsAxJAau7ZE1BbMt9MiWk
Retrying in 1 seconds...
Transaction sent: https://explorer.solana.com/tx/5v57QcLgRYbUGryYhjdMjyYx8eabfweJN2q4kqKgXW61VBQD1hhiCMyQJGQbRp3YbZD5Wr8zfpaw2VJRBU2NXM9A
Attempt 2 failed: Unable to confirm transaction 5v57QcLgRYbUGryYhjdMjyYx8eabfweJN2q4kqKgXW61VBQD1hhiCMyQJGQbRp3YbZD5Wr8zfpaw2VJRBU2NXM9A
Retrying in 2 seconds...
Transaction sent: https://explorer.solana.com/tx/3eJkGZ9YCJK5XufhpNS5hgE5xrhGd2XvCkm2A26LmaVu8qFZdH5jmEcWgYozNWfEHvm69iuqi2V7U8dypfrMjQs3
Transaction confirmed
Waiting for 20 seconds before selling...
Selling tokens with 20.0% slippage tolerance...
Traceback (most recent call last):
  File "trade.py", line 157, in <module>
    asyncio.run(main(yolo_mode=args.yolo, match_string=args.match, bro_address=args.bro, marry_mode=args.marry))
  File "/home/lukii/.pyenv/versions/3.8-dev/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/lukii/.pyenv/versions/3.8-dev/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "trade.py", line 140, in main
    await trade(websocket, match_string, bro_address, marry_mode, yolo_mode)
  File "trade.py", line 52, in trade
    await _trade(websocket, match_string, bro_address, marry_mode, yolo_mode)
  File "trade.py", line 107, in _trade
    sell_tx_hash = await sell_token(mint, bonding_curve, associated_bonding_curve, SELL_SLIPPAGE)
  File "/home/lukii/pump-fun-bot/sell.py", line 74, in sell_token
    token_balance = await get_token_balance(client, associated_token_account)
  File "/home/lukii/pump-fun-bot/sell.py", line 62, in get_token_balance
    if response.value:
AttributeError: 'solders.rpc.errors.InvalidParamsMessage' object has no attribute 'value'
