### ISSUE TITLE
Why every buy transcation will create a account ?

### ISSUE THREAD

**Issue by tigermumu** [chainstacklabs/pump-fun-bot#9]
Buy token step is :
step1 : SyQHeAf8fg2MipUQeKrcmjJf1CsArLKWGdKHcCEVLdMxfT7jm12f5NLZDW6S6eW4ffjDikZsjApVFZ4h4Ln5kz3
Associated Token Account Program: create

step2 :  5nhU6wbWboPs4jQMStmwenmPeVo916K91XSZT8sjrdFAQypbkatnSL3V9qpcwrHtt1oeQKjJsKPTjcPJ2tayykXE
Pump.fun: buy

Why have to create first? Could I pass step 1? 

![image](https://github.com/user-attachments/assets/ef7ea7e0-9c9b-421f-bf45-8beb02e92b12)

**Comment by akegaviar** [comment]
It needs an associated token account to hold the token you are buying.

**Comment by tigermumu** [comment]
Yes，I have already added create_ata_ix to 1 Tx.
